# See [Source Acceptance Tests](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/source-acceptance-tests.md)
# for more information about how to configure these tests
connector_image: airbyte/source-quickbooks-singer:dev
tests:
  spec:
    - spec_path: "source_quickbooks_singer/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      empty_streams: ["budgets", "classes", "departments", "payment_methods", "transfers", "vendor_credits"]
#  incremental:
#  This test is commented out, because singer tap expects LastUpdatedTime for each stream in state.
#  But records contain field MetaData with nested LastUpdatedTime. It causes test error.
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog.json"
#      future_state_path: "integration_tests/abnormal_state.json"
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
